/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package polyglotj;
import com.google.gson.Gson;
import java.net.Socket;
import java.net.InetSocketAddress;
import java.io.InputStreamReader;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.IOException;

public class Polyglot {
	public static Gson gson = new Gson();
	private static Polyglot instance = null;
	private Socket server;
	private BufferedReader in;
	private PrintWriter out;
	private Polyglot() throws IOException {
		server = new Socket();
		server.connect(new InetSocketAddress("localhost", 8080)); // TODO: Parameterize
		in = new BufferedReader(new InputStreamReader(server.getInputStream()));
		out = new PrintWriter(server.getOutputStream());
		out.println(gson.toJson(new Message("register", "java", "", "")));
	}

	public void send_to(String language, Object msg) {
		send_to(language, msg, "send");
	}

	public void send_to(String language, Object msg, String purpose) {
		out.println(gson.toJson(new Message(purpose, "java", language, msg)));
	}

	private Message parseJson(String s) { return gson.fromJson(s, Message.class); }

	public Message receiveNowait() throws IOException {
		return parseJson(in.readLine());
	}

	public Message receive() throws IOException {
		String j = in.readLine();
		while (j == null) { j = in.readLine(); }
		return parseJson(j);
	}

	public static Polyglot getInstance() throws IOException {
		if (instance == null) {
			instance = new Polyglot();
		}
		return instance;
	}
}
